source :rubygems

gem 'nanoc'
gem 'sass'
gem 'compass'
gem 'zurb-foundation'
gem 'nanoc-javascript-concatenator'
gem 'builder'
gem 'listen'
#gem 'rb-inotify', '~> 0.9'
gem 'nanoc-image-compressor', '>= 0.1.0'
gem 'kramdown'
gem 'uglifier'
gem 'rake'
gem 'rack'
gem 'mime-types'
gem 'i18n'
gem 'therubyracer', '0.10.1'